import { profile } from "console";
import { test, expect } from "../fixtures/hooks-fixture";
import { LeftNavigation } from "../pages/LeftNavigation";
import { PimPage } from "../pages/PimPage";
import { TestData } from "../utils/TestData";
const data = new TestData();
const employee = data.generateEmployee();

test("Add Employee with autogenerated Employee ID", async ({
  page,
  gotoUrl,
  leftNavigation,
  pimPage,
}) => {
  await leftNavigation.openPimTab();
  await pimPage.addEmployee(
    employee.firstName,
    employee.lastName,
    employee.middleName
  );
  await expect(pimPage.personalDetailsHeader).toHaveText("Personal Details");
});
test("Add Employee with custom Employee ID", async ({
  page,
  gotoUrl,
  leftNavigation,
  pimPage,
}) => {
  await leftNavigation.openPimTab();
  await pimPage.addEmployee(
    employee.firstName,
    employee.lastName,
    employee.middleName,
    employee.employeeId
  );
  await expect(pimPage.personalDetailsHeader).toHaveText("Personal Details");
});

test("Add Employee with only mandatory details", async ({
  page,
  gotoUrl,
  leftNavigation,
  pimPage,
}) => {
  await leftNavigation.openPimTab();
  await pimPage.addEmployee(employee.firstName, employee.lastName);
  await expect(pimPage.personalDetailsHeader).toHaveText("Personal Details");
});
test("Adding Employee with blank details shows validation errors", async ({
  page,
  gotoUrl,
  leftNavigation,
  pimPage,
}) => {
  await leftNavigation.openPimTab();
  await pimPage.addEmployeeButton.click();
  await pimPage.saveButton.click();
  expect(await pimPage.firstNameFieldError.textContent()).toBe("Required");
  expect(await pimPage.lastNameFieldError.textContent()).toBe("Required");
});
test("Add Employee with login details", async ({
  page,
  gotoUrl,
  leftNavigation,
  pimPage,
}) => {
  await leftNavigation.openPimTab();
  await pimPage.addEmployeeWithLoginDetails(
    employee.firstName,
    employee.lastName,
    employee.username,
    employee.password,
    employee.confirmPassword,
    employee.middleName,
    employee.employeeId
  );
  await expect(pimPage.personalDetailsHeader).toHaveText("Personal Details");
});
